config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'  # Página de login
  post '/login', to: 'sessions#create'  
  delete '/logout', to: 'sessions#destroy' 
  
  resources :users
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :users
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :group, optional: true

  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true
  validates :task_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :group, optional: true
    has_many :tasks

    before_save { email.downcase! }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    
    validates :name, presence: true, length: { maximum: 30 }
    validates :last_name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    private

    def require_login
        unless logged_in?
            redirect_to login_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      #params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      # flash[:danger] = 'Invalid email/password combination' # Not quite right!
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :select_user, only: [:index, :new, :create]

  def index
    @tasks = @user.tasks # Obtener todas las tareas del usuario

    @group_tasks = []
    
    if @user.group.present?
      @group_tasks += @user.group.tasks
    end

    @tasks += @group_tasks # Combinar las tareas del usuario y las tareas de los grupos en una única lista

    # Puedes ordenar las tareas según tus requisitos, por ejemplo:
    # @tasks.sort_by!(&:due_date)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new()
  end

  def create
    @task = Task.new(task_params)
    @task.status = "false"
    @task.user_id = @user.id
    if @task.task_type == "grupal"
      @task.group_id = @user.group.id
    end

    if @task.save
      flash[:success] = "Task created"
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
  def select_user
    @user = current_user
  end

  # strong params
  def task_params
    params.require(:task).permit(:name, :description, :due_date, 
      :status, :user_id, :group_id, :task_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    # debugger
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to  @user          # redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Gestor de Tareas"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Gestor de Tareas
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", '#' %></li>
            <li><%= link_to "Contact", '#' %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "Task Manager", root_path, id: "logo" %>
    <nav>
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        </div>

        <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
                        id="bs-example-navbar-collapse-1">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", '#' %></li>
            <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_task_error_messages.html.erb
<% if @task.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@task.errors.count, "error") %>.
        </div>
        <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/tasks/index.html.erb
<!-- app/views/tasks/index.html.erb -->
<%= link_to 'Nueva Tarea', new_task_path, class: 'btn btn-outline-dark' %>

<h3>Tareas Personales</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Tarea</th>
      <th scope="col">Descripción</th>
      <th scope="col">Fecha Límite</th>
      <th scope="col">Estado</th>
      <th scope="col">Editar</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_type == 'personal' %>
        <tr class="<%= task.status ? '' : 'table-dark' %>">
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.due_date %></td>
          <td><%= task.status ? 'Completada' : 'Pendiente' %></td>
          <td><%= link_to 'Editar', edit_task_path(task) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h3>Tareas en Grupo</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Tarea</th>
      <th scope="col">Descripción</th>
      <th scope="col">Fecha Límite</th>
      <th scope="col">Estado</th>
      <th scope="col">Editar</th>
      <th scope="col">Grupo</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_type == 'grupal' %>
        <tr>
          <td class="<%= task.status == false ? 'text-decoration-line-through' : '' %>"><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.due_date %></td>
          <td><%= task.status ? 'Completada' : 'Pendiente' %></td>
          <td><%= link_to 'Editar', edit_task_path(task) %></td>
          <td><%= task.group.present? ? task.group.name : 'Tareas personales' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>Crear una tarea nueva</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @task, local: true) do |f| %>
            <%= render 'shared/task_error_messages' %>
        
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :due_date %>
                <%= f.datetime_field :due_date, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :task_type %>
                <%= f.select :task_type, { "Personal" => "personal", "Grupal" => "grupal" }, { prompt: "Seleccionar tipo de tarea" }, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.submit "Crear", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1>Update your profile</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/user_error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="https://gravatar.com/emails" target="_blank">change</a>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/user_error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>